### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by EternalAzure** [Juustoisa/ot-harjoitustyo#1]
Arvioitava versio:  2.5.2021 klo 11:30

Aloitin lukemalla vaatimusmäärittelyn ja dokumentaation. Oikein kiva sovellusidea. 
Näistä sai ihan hyvän kuvan ohjelman toiminnasta. Tietysti ei ole pahitteeksi laittaa 
pari sanaa dokumentaatioon. Ohjelman ja testit sai ajettua ohjeita noudattamalla ja 
jar tiedoston luominen ja ajaminen sujui myös mutkatta. Vaatimusmäärittelyssä 
toimivaksi ilmoitetut ominaisuudet toimivat. 

``` 
- [x] Käyttäjän on mahdollista lisätä tee tietokantaan, teelle voi asettaa nimen, teelaadun, pistemäärän, hinnan, paljonko teetä on jäljellä ja paljonko teetä kuluu kerralla.
- [x] Lisättyjen teitten varastomääriä voi selata.
- [ ] Lisätylle teelle voi kirjoittaa muistiinpanoja, teen tietoja voi päivittää.
 ```
Saat vaatimusmäärittelyn tehty-merkinnät ohjeistuksen mukaiseksi

Tietokanta säilyttää tietoa kuten pitää ja ohjelma on suojattu sql-injektioilta. 
ON DELETE CASCADE on hyvä lisä. Otankin sen nyt itse käyttöön. 
Myös NumberUtils.isParsable() oli kiinnostava tapa validoida numeroita. 
Opin myös mikä on Arrays.fill() ja String.format. 
Kaiken kaikkiaan selkolukuista koodia ja pakkausten ja luokkien sisältö on johdonmukainen.
Myös luokkien väliset riippuvuudet ovat fiksut. Db tai kontrolleri ei tunne käyttöliittymää.

__Varoituksen sana:__
Jos useampi metodi kutsuu luokan Db palveluita voi olla hyvä idea heittää SQLException ja hoitaa 
se vasta siellä missä palvelua kutsuttiin. Huonosti hoidettu poikkeus vain piilottaa ongelman.
Näyttää kuitenkin siltä että kaikki on kunnossa.

__Ideoita__
Ui luokan start metodin voi hajottaa viiteen osaan yksi jokaiselle scenelle.
TeaController on nimetty lyhyesti tC, joka toimii, mutta jos projekti kasvaa muuttuu kuvaavampi nimeäminen välttämättömäksi.
addTeaButton kanssa pitkän validaation voi muuttaa omaksi metodikseen. 
Rittää, että Alert ikkunasta tekee yhden instanssin ennen setOnAction määrittelyä. 
Tietokannan taulua 'teas' luodessa voi asettaa name ominaisuudeksi ```UNIQUE```. Näin vältytään duplikaateilta. 
Koodissa on paljon käyttämättömiä importteja joita sopii siistiä pois.

**Comment by Juustoisa** [comment]
Joo kiitos, hyviä pointteja. :)
